### ISSUE TITLE
Define thresholds in check_ldap_monitor.pl currentconnexions

### ISSUE THREAD

**Issue by imejri** [ltb-project/nagios-plugins#14]
hi,
How to define the -w -c options in the ldap_monitor script. what is the best value to choose please.
The same thing about a number of threads.

thx

**Comment by sophieqc** [comment]
Hello,

Are you talking about "check_ldap_monitor.pl" ? If so, this script can check multiple things with different thresholds, also thresholds depends on your specific architecture and its limits and what level of service you want to achieve.

Please check the documentation : https://ltb-project.org/documentation/nagios-plugins/check_ldap_monitor

**Comment by imejri** [comment]
thank you pcurie,
for an ldap directory with 50000 entry , with an mdb backend. what is the best choice of this thresholds?
you now a benchmark the ca i help me please?
thx very much

**Comment by sophieqc** [comment]
You didn't specify witch check you want to use in this script ?

For benchmarking I would recommend "ldclt", this tool comes with 389DS directory but can be used against any LDAP directory.

**Comment by imejri** [comment]
hi paul,
i want to check the currentconnexions.

**Comment by sophieqc** [comment]
Okay so the ideal values for that would depend on your configuration/resources, i can't give you a number even if you told me, you need to run a benchmark to see how much your machine/vm can handle.

Hope that helps

**Comment by coudot** [comment]
@imejri as told by Paul, limits depend on your system settings (RAM/CPU/Network bandwith/...)

For current connections, I suggest to put a warning at 500 and a critical at 800. OpenLDAP could handle more than 1000 established connections but this can impact performances.

**Comment by imejri** [comment]
@coudot in my case i have more the 1500 connections !!! i have a database with 50000 users/applications that connect with a web sso LemonLdap ! i don't now if this is a normal behavior ??

**Comment by coudot** [comment]
You can indeed have a lot of connections referenced in cn=monitor, that are alive but non used. But if only LL::NG connects to your LDAP, it is not normal, you need to see which applications are opening connections and not closing them.

On the other side, if you don't experience any performance problem, you can adapt your monitoring thresholds.

**Comment by imejri** [comment]
thank you @coudot

**Comment by imejri** [comment]
hi,
in ldap_time_response , how many threads can i use ?

**Comment by coudot** [comment]
The default is 5 and seems a good value.

**Comment by imejri** [comment]
this command gives me:
ps -axH |grep slapd|wc -l
19
does mean that i have 19 threads for my slapd daemon ?

and an ldapsearch on the monitor database gives me: cn=max,cn=threads,cn=monitor

**cn: max**
**monitoredInfo: 16**

**Comment by coudot** [comment]
Hello @imejri 

I close this issue, it seems you got all needed answers.
