### ISSUE TITLE
Clarify why the relative sum of used and free pages is not 100%

### ISSUE THREAD

**Issue by dilyanpalauzov** [ltb-project/nagios-plugins#19]
`check_lmdb_usage.pl` and `check_ldap_monitor.pl` read
```
  Max pages: 768
  Number of pages used: 148
  Free pages: 31
```
And calculate:

* per cent of free pages = 31 * 100 / 768 = 4.03%
* per cent of used pages = 148 * 100 / 768 = 19.27%

Contrary to intuition, the sum of the per cent is not 100.

I kindly ask to extend the documentation and include explanation, why the sum is not 100%.

With this explanation it will be easier to understand what OpenLDAP monitoring does and what one wants really to monitor.

**Comment by davidcoutadeur** [comment]
Done in a042bdd
+ in documentation: https://ltb-project.org/documentation/check_lmdb_usage.html

**Comment by davidcoutadeur** [comment]
I reopen for doing a new release

**Comment by dilyanpalauzov** [comment]
The example at https://ltb-project.org/documentation/check_lmdb_usage.html is:
> OK - 66% pages used / 16% pages free

In this example the sum used + free is not 100%

**Comment by davidcoutadeur** [comment]
I have just updated the examples in https://github.com/ltb-project/documentation/commit/8c1fce4282e949b2a6b8b99b9c8b77c21fc9516f

The sum is now 100%: (1% of difference due to the rounded value)

```
OK - 65% pages used / 34% pages free
```
