### ISSUE TITLE
when check_lmdb_usage cannot find mdb_stat we get a Illegal division by zero

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [ltb-project/nagios-plugins#8]
Hello,

i use check_lmdb_usage and forgot to install mdb_stat, i got this error

check_lmdb_usage.pl -S /usr/bin/mdb_stat -H /var/lib/ldap/ -w 80 -c 90
Can't exec "/usr/bin/mdb_stat": No such file or directory at ./check_lmdb_usage.pl line 195.
Illegal division by zero at ./check_lmdb_usage.pl line 217.

Cheers

**Comment by coudot** [comment]
Thanks for the report, we indeed to catch better this error.

**Comment by coudot** [comment]
We now check the mdb_stat binary and also the db_home parameter
